/**
 * Contributions feed — /public/contributions/index.json (generated by
 * scripts/fetch-contributions.mjs). Shared by the home strip and the
 * contributions page.
 */

import { withBase } from '@/config/site'

export interface Contribution {
  id: string
  /** "patch" (PR) | "advisory" */
  type: string
  title: string
  summary: string
  repo: string
  url: string
  /** ISO datetime */
  date: string
  /** "merged" | "published" | "open" | … */
  state: string
  tags: string[]
}

let cache: Contribution[] | null = null

/** All contributions, newest first. Cached after first fetch. */
export async function loadContributions(): Promise<Contribution[]> {
  if (cache) return cache
  const res = await fetch(withBase('/contributions/index.json'))
  if (!res.ok) throw new Error(`failed to load contributions: ${res.status}`)
  const raw = (await res.json()) as { items: Contribution[] }
  cache = [...(raw.items ?? [])].sort((a, b) => (a.date < b.date ? 1 : -1))
  return cache
}

/** "08 Jun 2026" */
export function formatContributionDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      timeZone: 'UTC',
    })
  } catch {
    return iso
  }
}
